# Generated by Django 6.0.7 on 2026-08-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="agenda_configurada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professor",
            name="nome_exibicao",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="DisponibilidadeProfessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidades",
                        to="conta.professor",
                    ),
                ),
            ],
            options={
                "ordering": ["dia_semana", "hora_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("professor", "dia_semana", "hora_inicio", "hora_fim"),
                        name="unique_disponibilidade_professor",
                    )
                ],
            },
        ),
    ]
