# Generated by Django 6.0.7 on 2026-09-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conta", "0002_professor_agenda_configurada_professor_nome_exibicao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disponibilidadeprofessor",
            options={"ordering": ["dia_semana", "horario"]},
        ),
        migrations.RemoveConstraint(
            model_name="disponibilidadeprofessor",
            name="unique_disponibilidade_professor",
        ),
        migrations.RenameField(
            model_name="disponibilidadeprofessor",
            old_name="hora_fim",
            new_name="horario",
        ),
        migrations.AddConstraint(
            model_name="disponibilidadeprofessor",
            constraint=models.UniqueConstraint(
                fields=("professor", "dia_semana", "horario"),
                name="unique_disponibilidade_professor",
            ),
        ),
        migrations.RemoveField(
            model_name="disponibilidadeprofessor",
            name="hora_inicio",
        ),
    ]
