# Generated by Django 6.0.7 on 2026-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conta", "0003_alter_disponibilidadeprofessor_options_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="conteudo",
            constraint=models.UniqueConstraint(
                fields=("tema", "nome"), name="unique_conteudo_tema_nome"
            ),
        ),
        migrations.AddConstraint(
            model_name="disciplina",
            constraint=models.UniqueConstraint(
                fields=("professor", "nome"), name="unique_disciplina_professor_nome"
            ),
        ),
        migrations.AddConstraint(
            model_name="tema",
            constraint=models.UniqueConstraint(
                fields=("disciplina", "nome"), name="unique_tema_disciplina_nome"
            ),
        ),
    ]
