# Generated by Django 6.0.7 on 2026-10-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_conteudo_unique_conteudo_tema_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplina",
            name="cor",
            field=models.CharField(default="#3b82f6", max_length=7),
        ),
    ]
