# Generated by Django 6.0.7 on 2026-08-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0002_matricula"),
        ("disciplinas", "0002_materia_conteudo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiarioDeBordo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diario",
                        to="alunos.matricula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diário de Bordo",
                "verbose_name_plural": "Diários de Bordo",
            },
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("observacao", models.TextField()),
                (
                    "conteudos",
                    models.ManyToManyField(blank=True, to="disciplinas.conteudo"),
                ),
                (
                    "diario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="registros.diariodebordo",
                    ),
                ),
                (
                    "materias",
                    models.ManyToManyField(blank=True, to="disciplinas.materia"),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
    ]
